[project]
name = "{{ cookiecutter.project_slug }}"
version = "0.0.1"
description = "{{ cookiecutter.project_description }}"
authors = [
    {name = "{{ cookiecutter.author_name }}", email = "{{ cookiecutter.author_email }}"}
]
readme = "README.md"
requires-python = "^{{ cookiecutter.python_version }}"
dependencies = [
    {% if cookiecutter.project_type == "api" %}
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    {% endif %}
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.3",
    "ruff>=0.1.3",
    "mypy>=1.6.1",
    "black>=23.10.1",
    "pipdeptree>=2.13.0",
]

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "B", "I"]
line-length = 88

[tool.poetry]
package-mode = true 